/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/frontend/**/*.{js,jsx,ts,tsx,html}"],
  theme: {
    extend: {
      fontFamily: {
        marcellus: ["Marcellus", "serif"],
        roboto: ["Roboto Mono", "monospace", "sans-serif"],
        nunito: ["Nunito", "sans-serif"],
        lumanosimo: ["Lumanosimo", "serif"],
      },
      colors: {
        shade: {
          100: "#f7f7f7",
          200: "#eaeaea",
          300: "#B6B6B6",
          400: "#858585",
          500: "#575757",
          600: "#2D2D2D",
        },
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-purple-400",
    "bg-blue-400",
    "bg-green-400",
    "bg-yellow-400",
    "text-purple-100",
    "text-blue-100",
    "text-green-100",
    "text-yellow-100",
    "bg-purple-600",
    "bg-blue-600",
    "bg-green-600",
    "bg-yellow-600",
    "border-purple-800",
    "border-blue-800",
    "border-green-800",
    "border-yellow-800",
    "text-purple-800",
    "text-blue-800",
    "text-green-800",
    "text-yellow-800",
    "text-purple-400",
    "text-blue-400",
    "text-green-400",
    "text-yellow-400",
  ],
};
